chef/cookbooks/ceph/recipes/osd.rb

Currently ceph does not properly detect SLE12 and believes
it is a Sysvinit distribution. Add workaround for that (related to
bnc#914458)

Activate OSD properly on SLE12

---

chef/cookbooks/ceph/recipes/cinder.rb
chef/cookbooks/ceph/recipes/default.rb
chef/cookbooks/ceph/recipes/glance.rb
chef/cookbooks/ceph/recipes/mon.rb
chef/cookbooks/ceph/recipes/nova.rb
chef/cookbooks/ceph/recipes/osd.rb
chef/cookbooks/ceph/recipes/radosgw_apache2.rb
chef/cookbooks/ceph/recipes/radosgw_keystone.rb
chef/cookbooks/ceph/recipes/server.rb

On SLE12, ceph was split into ceph-common (client parts of
the package) and "ceph" (including the server part and depending
on the client). Install the packages appropriately as
the ceph server is removed from SLE11.

Properly install ceph server and client packages

---

chef/cookbooks/ceph/recipes/nova.rb

Starting with SLE12, the qemu will be natively rbd enabled.

Only install kvm-rbd-plugin on SLE11 and lower

---

chef/cookbooks/ceph/templates/default/rgw.conf.erb

The swift client is passing in the keystone token, which is
significantly larger than the default maximum header size.

Fix compatibility with Swift client (bnc#915753)

---

chef/cookbooks/ceph/recipes/radosgw_apache2.rb
chef/cookbooks/ceph/templates/default/rgw.conf.erb

This is much more useful than logging the IP address of the haproxy
server.
This depends on https://github.com/crowbar/barclamp-pacemaker/pull/171

 radosgw: Use X-Forwarded-For IP address in logs when behind haproxy

---

chef/cookbooks/ceph/recipes/radosgw_ha.rb

There's no real point in having all nodes try to update all pacemaker
resources all the time, and it actually can lead to issues due to races
when two non-founder nodes try to update the resource at the same time.
It's worth mentioning that for service LWRP, we actually want to do a
:start on each run to ensure that the service is restarted in case it
crashed. For pacemaker resources, the :start doesn't need to be done all
the time: as a crash of the service is caught by pacemaker already. So
if the founder goes missing, this won't hurt us.
http://bugzilla.suse.com/show_bug.cgi?id=918104

Only deal with pacemaker resources on the founder node (bnc#918104)

---

chef/cookbooks/ceph/recipes/mon.rb

This can actually happen if all ceph nodes are reinstalled (without
being forgotten).

Update secrets attributes when they change

---

chef/cookbooks/ceph/recipes/osd.rb
chef/data_bags/crowbar/bc-template-ceph.json

There's a few odd edge cases with different settings for disk_mode and use_ssd_for_journal:
* If you've only got one disk, and you're using SSDs, that disk ends up being allocated as a journal with no OSD.
* Using disk_mode == first doesn't work with SSDs (again, you get a single journal and no OSD).
* On a system with all SSDs, you end up with only journals, and no OSDs.
This set of commits makes the following changes in order to remedy the above:
1. Default disk_mode to "all" (no real world deployment is ever going to want to only allocate the first disk and no others in a storage node).
2. If someone really wants to use disk_mode == "first", just allocate the first disk as an OSD, regardless of whether it's an SSD or HDD.
3. When first deploying, if the node only has one type of disk, …

Fix use_ssd_for_journal edge cases

---

chef/cookbooks/ceph/providers/client.rb

The cookbook rely on chef search to find the mon secret. This doesn't work when
using an external ceph cluster (in which case there might even be no mon user).
Additionally, since we're specifying the admin key now for the ceph_client resource
adding additional --name and --key options seems superfluous.

Don't use mon user and secret anymore for managing auth settings

---

chef/cookbooks/ceph/recipes/osd.rb
chef/data_bags/crowbar/bc-template-ceph.json
chef/data_bags/crowbar/bc-template-ceph.schema
chef/data_bags/crowbar/migrate/ceph/021_min_osd_size.rb
crowbar_framework/app/models/ceph_service.rb

Disks 10GB or less result in weighting errors.  5GB is used for the
journal by default, so 20GB seems the safest minium to run with.  Note
that real-world deployments will be unlikely to attempt to use disks
this small for OSDs, but it's not uncommon to run into problems with
small disks when testing toy clusters on virtual machines, which is why
we're now enforcing a minimum size.
Signed-off-by: Tim Serong <tserong@suse.com>

Only use disks bigger than 20GB (bnc#886795)

---

chef/cookbooks/ceph/recipes/nova.rb

With the ceph client-side support entering SLES11, this feature is now
part of the kvm package directly and there's no kvm-rbd-plugin
subpackage anymore.

Do not install the kvm-rbd-plugin package on SLES11

---

chef/cookbooks/ceph/libraries/default.rb

Note this is an (almost) blind fix. Not sure if this is correct. But endless while loop in ```mon_secret``` should surely be addressed.

Avoid invalid search query when no mon or osd roles are found

---

chef/cookbooks/ceph/recipes/nova.rb

We had the case where a compute node had some bogus fsid attribute, totally breaking its ceph setup for nova. The solution is to forcefully use the fsid attribute of the mon when crowbar is used.
However, before we can do that, we also need to allow redefining the libvirt secret, as until now, it was not possible to change it.
https://bugzilla.suse.com/show_bug.cgi?id=923224

Correctly handle wrong fsid attribute and allow redefining the libvirt secret

---

chef/cookbooks/ceph/recipes/nova.rb

Backport of https://github.com/crowbar/barclamp-ceph/pull/145
We had the case where a compute node had some bogus fsid attribute, totally breaking its ceph setup for nova. The solution is to forcefully use the fsid attribute of the mon when crowbar is used.
However, before we can do that, we also need to allow redefining the libvirt secret, as until now, it was not possible to change it.
https://bugzilla.suse.com/show_bug.cgi?id=923224

[stoney] Correctly handle wrong fsid attribute and allow redefining the libvirt secret

---

chef/cookbooks/ceph/recipes/radosgw.rb

The use of the ceph_client resource means that we need the admin
keyring, and if the role is deployed on a node that has nothing else
ceph-related, then this currently fails because nothing creates the
keyring.

Fix deployment of radosgw when on a non-osd/mon node

---

chef/cookbooks/ceph/recipes/radosgw.rb

**Backport of https://github.com/crowbar/barclamp-ceph/pull/150 to tex**
The use of the ceph_client resource means that we need the admin
keyring, and if the role is deployed on a node that has nothing else
ceph-related, then this currently fails because nothing creates the
keyring.
https://bugzilla.suse.com/show_bug.cgi?id=930542
(cherry picked from commit 260e6d446bdaa3869cfcf81782f4c8f21d4580c0)

[tex] Fix deployment of radosgw when on a non-osd/mon node (bsc#930542)

---

chef/cookbooks/ceph/recipes/radosgw.rb

**Backport of https://github.com/crowbar/barclamp-ceph/pull/150 to tex**
The use of the ceph_client resource means that we need the admin
keyring, and if the role is deployed on a node that has nothing else
ceph-related, then this currently fails because nothing creates the
keyring.
https://bugzilla.suse.com/show_bug.cgi?id=930542
(cherry picked from commit 260e6d446bdaa3869cfcf81782f4c8f21d4580c0)

Fix deployment of radosgw when on a non-osd/mon node (bsc#930542)

---

crowbar.yml

This makes the Ceph barclamp a member of both openstack and
suse_enterprise_storage, so it'll appear in the correct group for both
SUSE OpenStack Cloud and SUSE Enterprise Storage deploys.
Signed-off-by: Tim Serong <tserong@suse.com>

Make member of suse_enterprise_storage

---

chef/cookbooks/ceph/attributes/radosgw.rb

With the move to SLE12, there's no LSB script used anymore and the RA
must be using the systemd service file now.

radosgw: Fix RA of radosgw

---

chef/cookbooks/ceph/attributes/conf.rb

Add config default attributes into conf.rb
ceph/attributes/conf.rb
default["ceph"]["config"]["osds_in_total"] = 0
default["ceph"]["config"]["replicas_number"] = 0
Fixing https://bugzilla.suse.com/show_bug.cgi?id=934064

Add config default attributes into conf.rb

---

chef/cookbooks/ceph/recipes/calamari.rb

This puts /etc/ceph/ceph.client.admin.keyring on the calamari host, so
it can be used for CLI admin commands, e.g.: `ceph -w`.
Signed-off-by: Tim Serong <tserong@suse.com>

Include ceph::keyring recipe in calamari recipe

---

chef/cookbooks/ceph/recipes/calamari.rb
chef/cookbooks/ceph/templates/default/calamari-httpd.conf.erb
chef/data_bags/crowbar/bc-template-ceph.json
chef/data_bags/crowbar/bc-template-ceph.schema
chef/data_bags/crowbar/migrate/ceph/031_add_calamari_ssl.rb
crowbar_framework/app/helpers/barclamp/ceph_helper.rb
crowbar_framework/app/views/barclamp/ceph/_edit_attributes.html.haml
crowbar_framework/config/locales/ceph/en.yml

Note that this change causes the barclamp to replace
/etc/apache2/conf.d/calamari.conf as shipped in the calamari-server
pacakge.  This should be fine as that file is %config(noreplace) in the
calamari-server specfile, so won't be clobbered if calamari-server is
upgraded later.
Signed-off-by: Tim Serong <tserong@suse.com>

Add support for deploying Calamari with HTTPS (bsc#915315)
